server:
  port: 8848
spring:
  application:
    name: client-one
  sleuth:
    sampler:
      propagation: 1
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411
  ## 配置rabbitmq
  rabbitmq:
    addresses: "39.106.189.180:5672"
    username: zjtx
    password: zjtxtest
    listener:
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true

# eureka配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    eureka-server-u-r-l-context: http://localhost:8761/eureka/


