server:
  port: 8849
spring:
  application:
    name: client-two
# eureka配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    eureka-server-u-r-l-context: http://localhost:8761/eureka/


