server:
  port: 8849
spring:
  application:
    name: client-two
  ## 配置sleuth和zipkin全链路监控
  sleuth:
    sampler:
      propagation: 1
    messaging:
      rabbit:
        enabled: true
  zipkin:
    ### 使用rabbitmq提交数据
    sender:
      type: web
    ### 使用web提交数据到zipkin
    base-url: http://localhost:9411
  ## 配置rabbitmq
  rabbitmq:
    addresses: "39.106.189.180:5672"
    username: zjtx
    password: zjtxtest
    listener:
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true

# eureka配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    eureka-server-u-r-l-context: http://localhost:8761/eureka/


