server:
  port: 5555
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    eureka-server-u-r-l-context: http://localhost:8761/eureka/
spring:
  application:
    name: test-zuul

# 开放所有actuator端口，方便查询routes
management:
  endpoints:
    web:
      exposure:
        include: "*"